name: V2 Dev Testing
on:
  push:
    tags:
      - 'v2*-dev*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    env:
      ASSET_PATH: dist/FlyByWire_Installer_Setup.exe
      ASSET_DIRECTORY: dist/
      ASSET_NAME: FlyByWire_Installer_Setup.exe
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Install system requirements
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine32 wine64

      - name: Package installer
        run: |
          npm run package && rm -rf ./dist/win-unpacked/

      - name: Upload to Bunny CDN
        env:
          BUNNY_BUCKET_PASSWORD: ${{ secrets.BUNNY_BUCKET_PASSWORD }}
          BUNNY_SECRET_TOKEN: ${{ secrets.BUNNY_SECRET_TOKEN }}
        run: ./scripts/cdn.sh dist/ installer/dev
